// Local interaction model only. A backend must enforce identity and event access.
const friends=[{username:'maya',name:'Maya',sample:true},{username:'noah',name:'Noah',sample:true},{username:'alex_chen',name:'Alex',sample:true}];
const chosenFriends=new Set();
function friendLabel(id){const f=friends.find(f=>f.username===id);return f?`${f.name} (@${f.username})`:`@${id}`;}
function renderFriends(){
 document.getElementById('friend-list').innerHTML=friends.map(f=>`<label class="friend-option"><input type="checkbox" value="${escapeText(f.username)}" ${chosenFriends.has(f.username)?'checked':''}><span>${escapeText(friendLabel(f.username))}<small>${f.sample?'Sample shared availability':'Availability not connected'}</small></span></label>`).join('');
 document.querySelectorAll('#friend-list input').forEach(el=>el.onchange=()=>{el.checked?chosenFriends.add(el.value):chosenFriends.delete(el.value);document.getElementById('time-suggestions').innerHTML='';});
}
document.getElementById('open-friends').onclick=()=>{renderFriends();document.getElementById('friends-dialog').showModal();};
document.getElementById('close-friends').onclick=()=>document.getElementById('friends-dialog').close();
document.getElementById('add-friend-form').onsubmit=e=>{e.preventDefault();const input=document.getElementById('friend-name'),id=input.value;const error=document.getElementById('friend-error');if(!/^[A-Za-z][A-Za-z0-9_]{2,23}$/.test(id)){error.textContent='Use 3–24 letters, numbers, or underscores, starting with a letter.';return;}if(id.toLowerCase()===profileState.username.toLowerCase()){error.textContent='That is your own username.';return;}if(friends.some(f=>f.username.toLowerCase()===id.toLowerCase())){error.textContent='This person is already in your demo friends.';return;}friends.push({username:id,name:id,sample:false});error.textContent=`@${id} added to this demo. No real friend request was sent.`;input.value='';renderFriends();};
function socialFields(host,plan={}){
 host.innerHTML=`<details class="social-details" open><summary>Invite friends</summary><p class="social-note">Invited people can see the details. Invitations are preview-only.</p><div class="invite-options">${friends.map(f=>`<label class="friend-option"><input type="checkbox" data-invite value="${escapeText(f.username)}" ${(plan.invitees||[]).includes(f.username)?'checked':''}><span>${escapeText(friendLabel(f.username))}</span></label>`).join('')}</div></details><details class="social-details"><summary>Who can see this plan?</summary><label class="social-field">Event visibility<select data-visibility aria-label="Event visibility"><option value="private" ${plan.visibility!=='friends'?'selected':''}>Only me & invited people</option><option value="friends" ${plan.visibility==='friends'?'selected':''}>My friends</option></select></label><p class="social-note">Everyone else sees “Busy.” The title, notes, type, and guest list stay hidden in their preview.</p><div data-exceptions><span class="control-caption">Show only Busy to these friends</span>${friends.map(f=>`<label class="friend-option"><input type="checkbox" data-block value="${escapeText(f.username)}" ${(plan.hiddenFrom||[]).includes(f.username)?'checked':''}><span>${escapeText(friendLabel(f.username))}</span></label>`).join('')}</div><div class="visibility-preview"><label>Preview as<select data-viewer aria-label="Preview as">${friends.map(f=>`<option value="${escapeText(f.username)}">${escapeText(friendLabel(f.username))}</option>`).join('')}<option value="other">Another person</option></select></label><div data-preview aria-live="polite"></div></div></details>`;
 host.querySelectorAll('select').forEach(enhanceSelect);
 function refresh(){const data=collectSocial(host);host.querySelector('[data-exceptions]').hidden=data.visibility!=='friends';host.querySelectorAll('[data-block]').forEach(input=>{input.disabled=data.invitees.includes(input.value);if(input.disabled)input.checked=false;});const viewer=host.querySelector('[data-viewer]').value;const projected=projectEvent({...plan,...collectSocial(host),title:plan.title||document.getElementById('plan-name').value||'Your plan',detail:plan.detail||'',time:plan.time||'Selected time'},viewer);host.querySelector('[data-preview]').textContent=projected.title==='Busy'?`${projected.time} · Busy`:`${projected.time} · ${projected.title}${projected.detail?' — '+projected.detail:''}`;}
 host.querySelectorAll('input,select').forEach(el=>el.addEventListener('change',refresh));refresh();
}
function collectSocial(host){return {invitees:Array.from(host.querySelectorAll('[data-invite]:checked'),el=>el.value),visibility:host.querySelector('[data-visibility]').value,hiddenFrom:Array.from(host.querySelectorAll('[data-block]:checked:not(:disabled)'),el=>el.value)};}
// Use a restricted projection; never include private fields in the viewer preview.
function projectEvent(plan,viewer){const allowed=(plan.invitees||[]).includes(viewer)||(plan.visibility==='friends'&&friends.some(f=>f.username===viewer)&&!(plan.hiddenFrom||[]).includes(viewer));return allowed?{title:plan.title,detail:plan.detail,time:plan.time}:{title:'Busy',time:plan.time};}
window.prepareSocialPlan=()=>{const type=document.getElementById('plan-type');if(!type.hidden)enhanceSelect(type);else{type.value='outing';type.parentElement.querySelector('.event-trigger').textContent='Outing ⌄';type.parentElement.querySelectorAll('[role=option]').forEach((el,i)=>el.setAttribute('aria-selected',String(i===0)));}socialFields(document.getElementById('plan-social'));};
window.readSocialPlan=()=>collectSocial(document.getElementById('plan-social'));
let sharingPlan=null;
window.openPlanSharing=index=>{sharingPlan=getPlansFor(dashboardState.selectedDate)[index];socialFields(document.getElementById('saved-plan-social'),sharingPlan);document.getElementById('sharing-dialog').showModal();};
document.getElementById('close-sharing').onclick=()=>document.getElementById('sharing-dialog').close();
document.getElementById('sharing-form').onsubmit=e=>{e.preventDefault();Object.assign(sharingPlan,collectSocial(document.getElementById('saved-plan-social')));renderAll();document.getElementById('sharing-dialog').close();};
function minuteOf(time){const match=time.match(/(\d+):(\d+)\s*(AM|PM)/i);return match?(+match[1]%12+(match[3].toUpperCase()==='PM'?12:0))*60+ +match[2]:720;}
function availableSlots(ids){const slots=[];for(let day=1;day<=7;day++){const date=new Date(today.getFullYear(),today.getMonth(),today.getDate()+day);for(const hour of [12,17,18,19]){const start=hour*60;const occupied=getPlansFor(date).some(p=>start<minuteOf(p.time)+60&&start+60>minuteOf(p.time));const sampleBusy=ids.some(id=>{const index=friends.findIndex(f=>f.username===id);return (date.getDay()+hour+index)%4===0;});if(!occupied&&!sampleBusy)slots.push({key:toKey(date),hour,label:date.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})+' · '+new Date(2026,0,1,hour).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})});}}return slots.slice(0,3);}
document.getElementById('find-times').onclick=()=>{const host=document.getElementById('time-suggestions'),ids=[...chosenFriends];if(!ids.length){host.textContent='Choose at least one friend first.';return;}if(ids.some(id=>!friends.find(f=>f.username===id)?.sample)){host.textContent='One of these friends has not shared availability yet. Try Maya, Noah, or Alex to explore the demo.';return;}const slots=availableSlots(ids);host.innerHTML=slots.length?'<p class="social-note">One-hour options using sample friend schedules and your current plans.</p>'+slots.map((s,i)=>`<button type="button" class="slot-option" data-slot="${i}"><strong>${s.label}</strong><span>Plan a hangout</span></button>`).join(''):'No shared hour found. Try a different group.';host.querySelectorAll('[data-slot]').forEach(button=>button.onclick=()=>{const slot=slots[+button.dataset.slot];document.getElementById('friends-dialog').close();selectDay(slot.key);document.getElementById('add-plan').click();document.getElementById('plan-name').value='Hangout with friends';for(const [id,value] of [['event-hour',slot.hour%12||12],['event-period',slot.hour>=12?'PM':'AM']]){const select=document.getElementById(id);select.value=value;select.parentElement.querySelector('.event-trigger').textContent=select.selectedOptions[0].textContent+' ⌄';select.parentElement.querySelectorAll('[role=option]').forEach((el,i)=>el.setAttribute('aria-selected',String(select.options[i].selected)));}syncPlanControls();socialFields(document.getElementById('plan-social'),{invitees:ids});});};
renderFriends();
