import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database} from '@/db/storage';
import {z} from 'zod';
const eventSchema=z.object({id:z.string().max(150).optional(),calendar:z.string().max(150),title:z.string().trim().min(1).max(160),start:z.string().max(50),end:z.string().max(50),location:z.string().max(300).default(''),invitees:z.string().max(1000).default(''),notes:z.string().max(2000).default(''),allDay:z.boolean().default(false)}).refine(e=>Number.isFinite(Date.parse(e.start))&&Number.isFinite(Date.parse(e.end))&&Date.parse(e.end)>Date.parse(e.start),'End time must be after start time.');
export async function POST(req:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in to save your changes.'},{status:401});if(req.headers.get('sec-fetch-site')==='cross-site')return Response.json({error:'Request not allowed.'},{status:403});try{const raw=await req.text();if(raw.length>2000000)return Response.json({error:'This import is too large.'},{status:413});const b=JSON.parse(raw),db=database(),owner=user.userId;
if(b.action==='calendar'){const name=z.string().trim().min(1).max(60).parse(b.name),id=crypto.randomUUID();await db.prepare('INSERT INTO calendars (id,owner,name,color) VALUES (?,?,?,?)').bind(id,owner,name,String(Number(b.color||1)%3)).run();return Response.json({id});}
if(b.action==='profile'){const p=z.object({name:z.string().trim().min(1,'Add a display name.').max(100),birthday:z.string().regex(/^$|^\d{4}-\d{2}-\d{2}$/),homeCity:z.string().trim().max(100),timeZone:z.string().trim().max(100),locationSharing:z.enum(['never','while_using','always'])}).parse(b.profile);await db.prepare('INSERT INTO profiles (owner,name,birthday,home_city,time_zone,location_sharing) VALUES (?,?,?,?,?,?) ON CONFLICT(owner) DO UPDATE SET name=excluded.name,birthday=excluded.birthday,home_city=excluded.home_city,time_zone=excluded.time_zone,location_sharing=excluded.location_sharing').bind(owner,p.name,p.birthday,p.homeCity,p.timeZone,p.locationSharing).run();return Response.json({ok:true});}
if(b.action==='delete'){const id=z.string().parse(b.id);await db.batch([db.prepare('DELETE FROM responses WHERE event=? AND EXISTS (SELECT 1 FROM events WHERE id=? AND owner=?)').bind(id,id,owner),db.prepare('DELETE FROM events WHERE id=? AND owner=?').bind(id,owner)]);return Response.json({ok:true});}
if(b.action==='save'||b.action==='import'){const input=b.action==='save'?[b.event]:b.events;const list=z.array(eventSchema).min(1).max(500).parse(input);const owned=(await db.prepare('SELECT id FROM calendars WHERE owner=?').bind(owner).all()).results.map((r:any)=>r.id);if(list.some(e=>!owned.includes(e.calendar)))return Response.json({error:'Calendar not found.'},{status:403});const statements=[];for(const e of list){const id=b.action==='save'&&e.id?e.id:crypto.randomUUID();if(e.id&&b.action==='save'){const existing=await db.prepare('SELECT id FROM events WHERE id=? AND owner=?').bind(id,owner).first();if(!existing)return Response.json({error:'Event not found.'},{status:404});statements.push(db.prepare('UPDATE events SET calendar=?,data=? WHERE id=? AND owner=?').bind(e.calendar,JSON.stringify({...e,id}),id,owner));}else statements.push(db.prepare('INSERT INTO events (id,owner,calendar,data,token) VALUES (?,?,?,?,?)').bind(id,owner,e.calendar,JSON.stringify({...e,id}),crypto.randomUUID()));}await db.batch(statements);return Response.json({ok:true,count:list.length});}
return Response.json({error:'Unknown action.'},{status:400});}catch(e){if(e instanceof z.ZodError)return Response.json({error:e.issues[0]?.message??'Check your event details.'},{status:400});console.error(e);return Response.json({error:'Could not save. Your changes have been kept in the form; please retry.'},{status:503})}}
